# Generated by Django 2.2.5 on 2019-09-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.FileField(blank=True, upload_to='post_image'),
        ),
    ]
