# Generated by Django 2.2.5 on 2019-09-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_person_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='Headshot_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
