# Generated by Django 2.2.4 on 2019-09-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_person_headshot_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='Headshot_image',
        ),
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='clients_photos'),
        ),
    ]
